// ─── Curriculum Data ───────────────────────────────────────────────────
const PHASES = [
  {
    id: 1,
    name: "Houdini Procedural Systems",
    weeks: [1, 2, 3, 4],
    color: "#7b9ab5",
    colorDim: "rgba(123,154,181,0.14)",
    goal: "Build a procedural RPG environment tool",
    tag: "PHASE 01",
  },
  {
    id: 2,
    name: "Python + Maya Pipeline Tools",
    weeks: [5, 6, 7, 8],
    color: "#c4a464",
    colorDim: "rgba(196,164,100,0.14)",
    goal: "Build an artist asset validator and export tool",
    tag: "PHASE 02",
  },
  {
    id: 3,
    name: "Shaders, Rendering & Optimization",
    weeks: [9, 10, 11, 12],
    color: "#8aaa90",
    colorDim: "rgba(138,170,144,0.14)",
    goal: "Build an optimized stylized material system",
    tag: "PHASE 03",
  },
];

const WEEKS = [
  // Phase 1
  {
    week: 1, phase: 1,
    title: "Houdini Fundamentals & SOP Networks",
    objectives: ["Understand VEX basics", "Build custom attribute workflows", "Learn SOP-level geometry manipulation"],
    tasks: ["Complete SOP network intro exercises", "Build a modular scatter system", "Document node graph with notes"],
    output: "Documented SOP scatter tool with VEX attributes",
    status: "complete",
    completion: 100,
    notes: "Solid foundation in wrangling. VEX attribute transfers clicked on day 3.",
    thumbs: ["thumb_w1_a", "thumb_w1_b"],
  },
  {
    week: 2, phase: 1,
    title: "Procedural Modeling & HDA Authoring",
    objectives: ["Create reusable HDAs", "Understand parameter promotion", "Build modular ruin pieces"],
    tasks: ["Author 3 ruin HDAs (wall, arch, floor)", "Set up digital asset library", "Parameter tuning and ranges"],
    output: "3 packaged HDAs for ruin environment kit",
    status: "complete",
    completion: 100,
    notes: "HDA promotion is powerful — exposed 12 parameters per asset.",
    thumbs: ["thumb_w2_a"],
  },
  {
    week: 3, phase: 1,
    title: "Terrain & Layout Systems",
    objectives: ["Build height-based scatter logic", "Slope masking for placement rules", "Integrate erosion passes"],
    tasks: ["Create terrain-aware scatter tool", "Implement slope/curvature masks", "Test with ruin kit pieces"],
    output: "Terrain-driven layout system with ruin placement",
    status: "in-progress",
    completion: 60,
    notes: "Slope masking working. Erosion pass WIP.",
    thumbs: [],
  },
  {
    week: 4, phase: 1,
    title: "Game Export & LOD Pipeline",
    objectives: ["FBX batch export from Houdini", "LOD generation strategy", "Collision mesh authoring"],
    tasks: ["Build export ROP network", "Generate 3 LOD levels per asset", "Package final RPG env tool"],
    output: "Fully packaged Procedural RPG Environment Generator",
    status: "upcoming",
    completion: 0,
    notes: "",
    thumbs: [],
  },
  // Phase 2
  {
    week: 5, phase: 2,
    title: "Python + Maya Fundamentals",
    objectives: ["Maya Python API overview", "Scene graph traversal", "Attribute query patterns"],
    tasks: ["Write scene query scripts", "Build basic UI with PySide2", "Author first validation check"],
    output: "Basic Maya Python toolkit scaffold",
    status: "upcoming",
    completion: 0,
    notes: "",
    thumbs: [],
  },
  {
    week: 6, phase: 2,
    title: "Asset Validation Logic",
    objectives: ["Name convention checking", "UV integrity validation", "Pivot and freeze transform checks"],
    tasks: ["Build 10 validation rules", "Error reporting system", "Batch-run on test assets"],
    output: "Validation rule library with error reporter",
    status: "upcoming",
    completion: 0,
    notes: "",
    thumbs: [],
  },
  {
    week: 7, phase: 2,
    title: "Export Pipeline & UI",
    objectives: ["FBX export automation", "Path and naming templates", "Progress logging"],
    tasks: ["Build export settings panel", "Hook validation into pre-export step", "Test on 20 sample assets"],
    output: "One-click export tool with integrated validation",
    status: "upcoming",
    completion: 0,
    notes: "",
    thumbs: [],
  },
  {
    week: 8, phase: 2,
    title: "Polish, GitHub & Documentation",
    objectives: ["Code cleanup and refactor", "README and usage docs", "GitHub publish"],
    tasks: ["Write docstrings for all functions", "Record demo video", "Publish to GitHub"],
    output: "Production-ready validator tool on GitHub",
    status: "upcoming",
    completion: 0,
    notes: "",
    thumbs: [],
  },
  // Phase 3
  {
    week: 9, phase: 3,
    title: "Shader Fundamentals & Graph Setup",
    objectives: ["Material graph architecture", "PBR vs stylized workflows", "Node optimization basics"],
    tasks: ["Build base stylized shader", "Set up master material system", "Document node categories"],
    output: "Master material template with stylized base",
    status: "upcoming",
    completion: 0,
    notes: "",
    thumbs: [],
  },
  {
    week: 10, phase: 3,
    title: "Texture Packing & Atlas Strategy",
    objectives: ["Channel packing techniques", "Atlas layout planning", "Memory budget targets"],
    tasks: ["Pack ORM textures for ruin kit", "Build atlas for environment tiles", "Measure memory footprint"],
    output: "Fully packed texture set with atlas documentation",
    status: "upcoming",
    completion: 0,
    notes: "",
    thumbs: [],
  },
  {
    week: 11, phase: 3,
    title: "Performance Profiling & Optimization",
    objectives: ["GPU profiling in engine", "Draw call analysis", "Material instancing"],
    tasks: ["Profile before/after states", "Reduce draw calls via instancing", "Document optimization gains"],
    output: "Optimization report with before/after comparison",
    status: "upcoming",
    completion: 0,
    notes: "",
    thumbs: [],
  },
  {
    week: 12, phase: 3,
    title: "Final Polish & Portfolio Render",
    objectives: ["Cinematic lighting pass", "Final render settings", "Portfolio presentation layout"],
    tasks: ["Light and render final environment", "Compile all three projects for portfolio", "Integrated case study writeup"],
    output: "Complete Stylized RPG Ruins Pipeline — portfolio ready",
    status: "upcoming",
    completion: 0,
    notes: "",
    thumbs: [],
  },
];

const RESOURCES = [
  { id: 1, title: "Houdini Procedural Workflows", type: "course", phase: 1, tool: "Houdini", week: 1, link: "#", notes: "Core SOP fundamentals, excellent pacing.", status: "completed", rating: 5, tags: ["procedural", "SOP", "fundamentals"] },
  { id: 2, title: "VEX for Artists", type: "documentation", phase: 1, tool: "Houdini", week: 1, link: "#", notes: "SideFX docs — bookmark the attribute reference.", status: "completed", rating: 5, tags: ["VEX", "attributes"] },
  { id: 3, title: "HDA Best Practices — SideFX", type: "article", phase: 1, tool: "Houdini", week: 2, link: "#", notes: "Great for parameter promotion patterns.", status: "in-progress", rating: 4, tags: ["HDA", "pipeline"] },
  { id: 4, title: "Technical Art in Games — GDC Talk", type: "video", phase: 1, tool: "General", week: 1, link: "#", notes: "Broad overview of TA role in production.", status: "completed", rating: 5, tags: ["overview", "production"] },
  { id: 5, title: "Maya Python for TDs", type: "course", phase: 2, tool: "Maya", week: 5, link: "#", notes: "PySide2 section is most relevant.", status: "not-started", rating: 0, tags: ["Python", "Maya", "pipeline"] },
  { id: 6, title: "Python MEL Scripting Reference", type: "documentation", phase: 2, tool: "Maya", week: 5, link: "#", notes: "", status: "not-started", rating: 0, tags: ["Python", "scripting"] },
  { id: 7, title: "Stylized Shader Techniques — Unreal", type: "tutorial", phase: 3, tool: "Shaders", week: 9, link: "#", notes: "Great breakdown of cel-shading approaches.", status: "not-started", rating: 0, tags: ["shaders", "stylized", "UE5"] },
  { id: 8, title: "GPU Optimization for Artists", type: "article", phase: 3, tool: "Optimization", week: 11, link: "#", notes: "Draw call reduction strategies.", status: "not-started", rating: 0, tags: ["optimization", "GPU"] },
];

// ─── Weekly portfolio pieces ────────────────────────────────────────────
const WEEKLY_PIECES = [
  { id:"w1",  week:1,  phase:1, title:"SOP Scatter System",       type:"Tool",    status:"complete",    tags:["Houdini","VEX","SOP"],          coverBg:"#c8d8e8", desc:"Custom point scatter with VEX attribute wranglers. Height, slope, and density control via ramp parameters.", images:4 },
  { id:"w2",  week:2,  phase:1, title:"Ruin Kit HDAs",            type:"Asset",   status:"complete",    tags:["Houdini","HDA","Modular"],       coverBg:"#bccedd", desc:"Three reusable digital assets: modular wall, arch, and floor sections. 12 exposed parameters per asset.", images:6 },
  { id:"w3",  week:3,  phase:1, title:"Terrain Layout System",    type:"Tool",    status:"in-progress", tags:["Houdini","Terrain","Scatter"],   coverBg:"#c0d4e0", desc:"Slope and curvature-based placement masks driving ruin scatter on generated terrain. Erosion pass WIP.", images:2 },
  { id:"w4",  week:4,  phase:1, title:"Game Export Pipeline",     type:"Tool",    status:"upcoming",    tags:["Houdini","FBX","LOD"],           coverBg:"#b8ccdc", desc:"Batch FBX export ROP network with automated LOD generation and collision mesh authoring.", images:0 },
  { id:"w5",  week:5,  phase:2, title:"Maya Python Toolkit",      type:"Tool",    status:"upcoming",    tags:["Python","Maya","PySide2"],       coverBg:"#ddd4b0", desc:"Scene graph traversal scripts and PySide2 UI scaffold for the validator pipeline.", images:0 },
  { id:"w6",  week:6,  phase:2, title:"Validation Rule Library",  type:"Tool",    status:"upcoming",    tags:["Python","Validation","Pipeline"],coverBg:"#d4c8a0", desc:"10 automated validation rules: naming, UVs, pivots, transforms, polygon count, material assignment.", images:0 },
  { id:"w7",  week:7,  phase:2, title:"One-Click Export Tool",    type:"Tool",    status:"upcoming",    tags:["Python","FBX","Automation"],    coverBg:"#ccc098", desc:"Full export panel with path templates, validation gating, and progress logging.", images:0 },
  { id:"w8",  week:8,  phase:2, title:"GitHub Release + Docs",    type:"Code",    status:"upcoming",    tags:["Python","GitHub","Docs"],        coverBg:"#c8b890", desc:"Polished release with docstrings, README, demo video, and public GitHub repo.", images:0 },
  { id:"w9",  week:9,  phase:3, title:"Master Stylized Shader",   type:"Shader",  status:"upcoming",    tags:["Shaders","UE5","Stylized"],     coverBg:"#b8ccb8", desc:"Master material with stylized base, cel-shading approximation, and custom parameters.", images:0 },
  { id:"w10", week:10, phase:3, title:"Texture Pack + Atlas",     type:"Texture", status:"upcoming",    tags:["Textures","ORM","Atlas"],        coverBg:"#a8c0a8", desc:"ORM channel packing for ruin kit assets and environment tile atlas with memory budget docs.", images:0 },
  { id:"w11", week:11, phase:3, title:"Optimization Report",      type:"Research",status:"upcoming",    tags:["GPU","Profiling","UE5"],         coverBg:"#b0c8b0", desc:"Before/after GPU profiling: draw calls 847→212, VRAM 1.2 GB→340 MB via instancing.", images:0 },
  { id:"w12", week:12, phase:3, title:"Final Portfolio Render",   type:"Render",  status:"upcoming",    tags:["Lighting","Render","Portfolio"], coverBg:"#a0bca0", desc:"Cinematic lighting pass and final renders of the complete Stylized RPG Ruins environment.", images:0 },
];

const PORTFOLIO_PROJECTS = [
  {
    id: "proj-houdini",
    title: "Procedural RPG Environment Generator",
    subtitle: "Houdini HDA Tool",
    phase: 1,
    status: "prototype",
    description: "A modular Houdini Digital Asset toolkit for procedurally generating RPG ruin environments. Features terrain-aware placement, height-based scatter logic, and a one-click FBX export pipeline.",
    tags: ["Houdini", "VEX", "Procedural", "HDA", "Game-Ready"],
    sections: ["Final Renders", "Node Graph", "Parameter Breakdown", "Variation Examples", "Exported Meshes", "Technical Breakdown"],
    coverColor: "var(--accent-blue)",
  },
  {
    id: "proj-python",
    title: "Artist Asset Validator & Export Tool",
    subtitle: "Python + Maya Pipeline Tool",
    phase: 2,
    status: "research",
    description: "A PySide2 Maya tool for validating and batch-exporting game assets. Runs 10+ automated checks (naming, UVs, transforms, pivots) before triggering a templated FBX export pipeline.",
    tags: ["Python", "Maya", "PySide2", "Pipeline", "Automation"],
    sections: ["UI Screenshots", "Validation Logic", "Error Reporting", "Export Pipeline", "GitHub", "Demo Video"],
    coverColor: "var(--accent-amber)",
  },
  {
    id: "proj-shaders",
    title: "Optimized Stylized Material System",
    subtitle: "Shaders + Rendering",
    phase: 3,
    status: "research",
    description: "A master material system for stylized environments with packed textures, atlas support, and instanced materials. Includes before/after GPU profiling and a full optimization report.",
    tags: ["Shaders", "UE5", "Optimization", "PBR", "Stylized"],
    sections: ["Final Renders", "Shader Graph", "Material Params", "Optimization Report", "Texture Packing", "Technical Explanation"],
    coverColor: "var(--accent-teal)",
  },
];

const STATUS_CONFIG = {
  "complete":     { label: "Complete",     color: "var(--accent-teal)",  bg: "rgba(80,210,180,0.12)" },
  "in-progress":  { label: "In Progress",  color: "var(--accent-amber)", bg: "rgba(240,168,48,0.12)" },
  "upcoming":     { label: "Upcoming",     color: "var(--text-dim)",     bg: "rgba(255,255,255,0.06)" },
  "portfolio-ready": { label: "Portfolio Ready", color: "#a0f080",      bg: "rgba(160,240,128,0.12)" },
  "research":     { label: "Research",     color: "var(--accent-amber)", bg: "rgba(240,168,48,0.12)" },
  "prototype":    { label: "Prototype",    color: "var(--accent-blue)",  bg: "rgba(56,182,255,0.12)" },
  "functional":   { label: "Functional",   color: "var(--accent-teal)",  bg: "rgba(80,210,180,0.12)" },
  "polish":       { label: "Polish",       color: "#c084fc",             bg: "rgba(192,132,252,0.12)" },
};

const STATS = {
  weeksCompleted: 2,
  currentWeek: 3,
  currentPhase: 1,
  portfolioPieces: 1,
  resourcesSaved: 8,
  filesUploaded: 14,
  overallProgress: 22,
};

Object.assign(window, { PHASES, WEEKS, RESOURCES, PORTFOLIO_PROJECTS, WEEKLY_PIECES, STATUS_CONFIG, STATS });
